version: '3.8'

services:
  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ${PWD}/backend/uploads:/app/uploads:rw
      - /app/__pycache__
    environment:
      - MONGODB_URL=mongodb://mongo:27017/resume_roaster
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    user: "${UID}:${GID}"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=resume_roaster

volumes:
  mongodb_data:
